### ISSUE TITLE
CUDA out of memory for a single core A100 80G GPU

### ISSUE THREAD

**Issue by leondelee** [tatsu-lab/stanford_alpaca#56]
I encountered the CUDA OOM on a single core A100 80G using your training code? Can i fix this by changing anything?

**Comment by yysjasmine** [comment]
> I encountered the CUDA OOM on a single core A100 80G using your training code? Can i fix this by changing anything?

Can you fix the OOM problem? I ran in to that problem as well using python 3.8 and pytorch 1.13.1，in a single core A100 80G.

**Comment by LuckyLee111** [comment]
Can you fix the OOM problem?I ran on 4 A100 30G and set the batch and epoch to 1 still have the OOM problem

**Comment by JoelNiklaus** [comment]
Thanks @dlwh. When switching to two A100 80GB GPUs it worked for me.

**Comment by zhl5842** [comment]
> Just to swoop in here, if you're using 6.7B or larger, 1 GPU (even an A100) isn't going to be enough without DeepSpeed Zero CPU Offload or Zero Infinity. At a minimum, to fine tune you need `6.7e9 * 4 bytes * 3 = 80.4GB` to store parameters and optimizer states (even in mixed precision, you want to store those in fp32)

why *3 ?

**Comment by dlwh** [comment]
Adam, the default optimizer, stores two momentum terms which are each the same size as the parameters themselves, so essentially three copies of the parameters... plus a fourth half-sized one (so, 14 bytes total) for the gradients, and then memory for activations that can range from "not very much" to a lot of extra GB.

2 A100s or Zero CPU offload should fix it right up.

**Comment by yysjasmine** [comment]
Thanks a lot, 2+ gpus worked fine.

**Comment by maziyarpanahi** [comment]
What was the batch size for those who could make it work with 2 A100 80GB GPUs? I have 4 and it fails

**Comment by JoelNiklaus** [comment]
For me it also worked with batch size 4 on 2 80GB A100 GPUs for sequence length 512.

**Comment by maziyarpanahi** [comment]
That's really strange, the default value for  model_max_length is already 512. With batch_size 1 it takes forever unfortunately
