### ISSUE TITLE
OOM after the last epoch

### ISSUE THREAD

**Issue by puyuanliu** [tatsu-lab/stanford_alpaca#65]
Got an OOM error after the training finished, not sure why. 

/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:2224: UserWarning: Failed to clone() tensor with name lm_head.weight. This may mean that this state_dict entry could point to invalid memory regions after returning from state_dict() call if this parameter is managed by FSDP. Please check clone implementation of lm_head.weight. Error: CUDA out of memory. Tried to allocate 502.00 MiB (GPU 1; 39.59 GiB total capacity; 35.54 GiB already allocated; 276.19 MiB free; 37.22 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by zdaiot** [comment]
@puyuanliu 
Hello, I also encountered the same problem. How did you solve it?

**Comment by muzhi1991** [comment]
I have fixed it, if you train model in gpu that memory smaller than author, you may find error such cuda oom when you save model after train(or save checkpoint, you only have broken file) .  This is because your model not offload to cpu, you can change `safe_save_model_for_hf_trainer` function as below:

```python
def safe_save_model_for_hf_trainer(trainer: transformers.Trainer, output_dir: str):
    """Collects the state dict and dump to disk."""
    # state_dict = trainer.model.state_dict()
    from torch.distributed.fsdp import (
        FullyShardedDataParallel as FSDP,
        MixedPrecision,
        BackwardPrefetch,
        ShardingStrategy,
        FullStateDictConfig,
        StateDictType,
    )
    model=trainer.model  
    save_policy = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
    with FSDP.state_dict_type(model, StateDictType.FULL_STATE_DICT, save_policy):
        cpu_state_dict = model.state_dict()
    if trainer.args.should_save:
        trainer._save(output_dir, state_dict=cpu_state_dict)  # noqa
```
this will save model successfully .
You can also Fix checkpoint error, if you use below custom Trainer
```python 
class CustomTriner(Trainer):
    def save_model(self, output_dir: Optional[str] = None, _internal_call: bool = False):
        if self.fsdp is not None:
            if output_dir is None:
                output_dir = self.args.output_dir
            from torch.distributed.fsdp import (
                FullyShardedDataParallel as FSDP,
                FullStateDictConfig,
                StateDictType,
            )
            save_policy = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
            with FSDP.state_dict_type(self.model, StateDictType.FULL_STATE_DICT, save_policy):
                cpu_state_dict = self.model.state_dict()
            if self.args.should_save:
                self._save(output_dir, state_dict=cpu_state_dict)  # noqa
            # Push to the Hub when `save_model` is called by the user.
            if self.args.push_to_hub and not _internal_call:
                self.push_to_hub(commit_message="Model save")
        else:
            super().save_model(output_dir, _internal_call)


data_module = make_supervised_data_module(tokenizer=tokenizer, data_args=data_args)
# replace Trainer
trainer = CustomTriner(model=model, tokenizer=tokenizer, args=training_args, **data_module)
trainer.train()
trainer.save_state()
# use trainer.save_model directly  will success, no need suse afe_save_model_for_hf_trainer
print("ready to save model")
trainer.save_model(training_args.output_dir)
```
Good Luck

**Comment by Jeffwan** [comment]
@muzhi1991 Thanks for the details. I used your way and OOM issue is gone but I eventually come into another problem. Seems that's a FSDP issue? Do you happen to know how to resolve this issue? Thanks!

```
{'train_runtime': 119.8187, 'train_samples_per_second': 2.504, 'train_steps_per_second': 0.075, 'train_loss': 1.2388523353470697, 'epoch': 2.57}
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [01:54<00:00, 12.76s/it]
[E ProcessGroupNCCL.cpp:828] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2778, OpType=_ALLGATHER_BASE, Timeout(ms)=1800000) ran for 1801649 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2778, OpType=_ALLGATHER_BASE, Timeout(ms)=1800000) ran for 1801649 milliseconds before timing out.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 5037) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
=====================================================
/tmp/FastChat/fastchat/train/train_mem.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-07_07:00:37
  host      : edf307caae46
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 5037)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 5037
=====================================================
```

**Comment by zdaiot** [comment]
@Jeffwan ，ref: https://github.com/tatsu-lab/stanford_alpaca/issues/81

**Comment by Lanxin1011** [comment]
> @muzhi1991 Thanks for the details. I used your way and OOM issue is gone but I eventually come into another problem. The program stuck at the model saving stage and timeout after ~30mins. Seems that's a FSDP issue? Do you happen to know how to resolve this issue? Thanks!
> 
> ```
> {'train_runtime': 119.8187, 'train_samples_per_second': 2.504, 'train_steps_per_second': 0.075, 'train_loss': 1.2388523353470697, 'epoch': 2.57}
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [01:54<00:00, 12.76s/it]
> [E ProcessGroupNCCL.cpp:828] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2778, OpType=_ALLGATHER_BASE, Timeout(ms)=1800000) ran for 1801649 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
> [E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=2778, OpType=_ALLGATHER_BASE, Timeout(ms)=1800000) ran for 1801649 milliseconds before timing out.
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 5037) of binary: /usr/bin/python
> Traceback (most recent call last):
>   File "/usr/local/bin/torchrun", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
>     run(args)
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> =====================================================
> /tmp/FastChat/fastchat/train/train_mem.py FAILED
> -----------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> -----------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-04-07_07:00:37
>   host      : edf307caae46
>   rank      : 0 (local_rank: 0)
>   exitcode  : -6 (pid: 5037)
>   error_file: <N/A>
>   traceback : Signal 6 (SIGABRT) received by PID 5037
> =====================================================
> ```

Hello there, sorry to bother. Have you solved the problem you encountered? I've got the same problem when saving the model and the persistent just not ended. Could you please provide me with your solution? And the solutions mentioned in issues #81 aiming at OOM problems seem to be invalid here. Really looking forward to your reply! Thanks~

**Comment by emranmohammadabuanas** [comment]
> I have fixed it, if you train model in gpu that memory smaller than author, you may find error such cuda oom when you save model after train(or save checkpoint, you only have broken file) . This is because your model not offload to cpu, you can change `safe_save_model_for_hf_trainer` function as below:
> 
> ```python
> def safe_save_model_for_hf_trainer(trainer: transformers.Trainer, output_dir: str):
>     """Collects the state dict and dump to disk."""
>     # state_dict = trainer.model.state_dict()
>     from torch.distributed.fsdp import (
>         FullyShardedDataParallel as FSDP,
>         MixedPrecision,
>         BackwardPrefetch,
>         ShardingStrategy,
>         FullStateDictConfig,
>         StateDictType,
>     )
>     model=trainer.model  
>     save_policy = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
>     with FSDP.state_dict_type(model, StateDictType.FULL_STATE_DICT, save_policy):
>         cpu_state_dict = model.state_dict()
>     if trainer.args.should_save:
>         trainer._save(output_dir, state_dict=cpu_state_dict)  # noqa
> ```
> 
> this will save model successfully . You can also Fix checkpoint error, if you use below custom Trainer
> 
> ```python
> class CustomTriner(Trainer):
>     def save_model(self, output_dir: Optional[str] = None, _internal_call: bool = False):
>         if self.fsdp is not None:
>             if output_dir is None:
>                 output_dir = self.args.output_dir
>             from torch.distributed.fsdp import (
>                 FullyShardedDataParallel as FSDP,
>                 FullStateDictConfig,
>                 StateDictType,
>             )
>             save_policy = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
>             with FSDP.state_dict_type(self.model, StateDictType.FULL_STATE_DICT, save_policy):
>                 cpu_state_dict = self.model.state_dict()
>             if self.args.should_save:
>                 self._save(output_dir, state_dict=cpu_state_dict)  # noqa
>             # Push to the Hub when `save_model` is called by the user.
>             if self.args.push_to_hub and not _internal_call:
>                 self.push_to_hub(commit_message="Model save")
>         else:
>             super().save_model(output_dir, _internal_call)
> 
> 
> data_module = make_supervised_data_module(tokenizer=tokenizer, data_args=data_args)
> # replace Trainer
> trainer = CustomTriner(model=model, tokenizer=tokenizer, args=training_args, **data_module)
> trainer.train()
> trainer.save_state()
> # use trainer.save_model directly  will success, no need suse afe_save_model_for_hf_trainer
> print("ready to save model")
> trainer.save_model(training_args.output_dir)
> ```
> 
> Good Luck

The code worked fro me to save the model. Now, I'm facing difficulty to load the model. Can you help me how to load the model?
