### ISSUE TITLE
Help with CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by GooDRomka** [tatsu-lab/stanford_alpaca#67]
I'm encountering an error in my code that says "RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
". I've checked that I have a compatible GPU and that it is properly installed on my machine, and I've installed the correct version of CUDA and the NVIDIA driver.

However, I'm still encountering this error and I'm not sure what to do next.
I would appreciate any help or advice you can provide on how to solve this issue. Please let me know if you need any more information or if there are any specific steps I should take to troubleshoot the problem.

**Comment by bartman081523** [comment]
please paste the complete error message (stacktrace).

**Comment by trizko** [comment]
in the torchrun command, I changed `--nproc_per_node=4` to `--nproc_per_node=1` and that fixed this error for me.

**Comment by GooDRomka** [comment]
> in the torchrun command, I changed `--nproc_per_node=4` to `--nproc_per_node=1` and that fixed this error for me.

Thanks, this really helped.

**Comment by Ahtesham00** [comment]
@GooDRomka where you able to train the model on single A100?
